### ISSUE TITLE
When do pre-process and post-process take place?

### ISSUE THREAD

**Issue by stereokai** [haoliangyu/html-webpack-processing-plugin#1]
With html-webpack-processing-plugin, when do pre-process and post-process take place?

Thanks :)

**Comment by haoliangyu** [comment]
This is a library working with [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) and it adds listeners to the event `html-webpack-plugin-before-html-processing` and `html-webpack-plugin-after-html-processing` (see [here](https://github.com/jantimon/html-webpack-plugin#events)).

So the pre-processing and post-processing take place before or after the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) creates the HTML file.

**Comment by stereokai** [comment]
Ah, thank you for that link! That satisfies my question :)
